# Generated by Django 4.2 on 2023-06-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='port',
            field=models.IntegerField(default=9001),
            preserve_default=False,
        ),
    ]
